endpoints:
  - name: sandbox
    target_url: http://biotimedxb.com:8007
    auth_type: token
    auth_api: http://biotimedxb.com:8007/api-token-auth/
    username: admin
    password_enc: "ZL6lFbyLrB1hXO/FIFUNabu2Bv5SohCGmbZO65eXGjKH"
    allowed:
      - path: /personnel/api/employees/
        methods: ["GET"]
      - path: /orders
        methods: ["GET"]
      - path: /products/list
        methods: ["GET"]
